# Generated by Django 4.2.5 on 2023-09-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.IntegerField()),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=250, null=True)),
                ('partner', models.CharField(max_length=40)),
                ('manager', models.CharField(max_length=40)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField(null=True)),
                ('budget', models.FloatField(null=True)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
