# Generated by Django 4.2.5 on 2023-10-04 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectName', models.CharField(max_length=100)),
                ('projectDescription', models.CharField(max_length=250, null=True)),
                ('partner', models.CharField(max_length=40)),
                ('manager', models.CharField(max_length=40)),
                ('startDate', models.DateField()),
                ('dueDate', models.DateField(null=True)),
                ('budget', models.FloatField(null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
